### ISSUE TITLE
Do you think this will catch up?

### ISSUE THREAD

**Issue by mrkkrp** [aelve/json-x#9]
Maybe `aeson` is not ideal (nothing is ideal), but it's definitely not broken. So why spend time fixing something that is not broken?

Moreover, I don't think this will get positive reaction and any significant adoption (although I thought the same about Megaparsec, but Parsec is effectively unmaintained, while last time I had a proposition for `aeson`, it was merged without problems).

There is also net (or “cascade” effect) in human society, that means that since `aeson` got there first and it's developed by a well-known person in the community, many projects, such as web frameworks are using it, and there is no way they will switch now to something else. The same with Megaparsec — it has got its users now apparently, but it will take long time for it to get at least 20% of Parsec's users, maybe forever.

For example, let's take QWERTY layout (let's say it's analogue of `aeson`) that is absolute nonsense, but Dvorak could not replace it once it QWERTY acquired critical degree of adoption, no matter how good Dvorak was. I think `aeson` has acquired it as well. The world is imperfect, and so are our tools.

----

Here is also a history from Common Lisp world. Common Lisp, being so powerful a language, gives you the ability to implement everything on your own, without help from your fellow programmers. For example,

> Dr. Mark Tarver — twice-quoted, above — wrote a dialect of Lisp called
> Qi. It is less than ten thousand lines of macros running atop Clisp. It
> implements most of the unique features of Haskell and OCaml. In some
> respects, Qi surpasses them. For instance, Qi's type inferencing engine is
> Turing complete. In a world where teams of talented academics were needed
> to write Haskell, one man, Dr. Tarver wrote Qi all by his lonesome.
>
> Read that paragraph, again, and extrapolate.
>
> Exercise for the reader: Imagine that a strong rivalry develops between
> Haskell and Common Lisp. What happens next?
>
> Answer: The Lisp Curse kicks in. Every second or third serious Lisp hacker
> will roll his own implementation of lazy evaluation, functional purity,
> arrows, pattern matching, type inferencing, and the rest. Most of these
> projects will be lone-wolf operations. Thus, they will have eighty percent
> of the features that most people need (a different eighty percent in each
> case). They will be poorly documented. They will not be portable across
> Lisp systems. Some will show great promise before being abandoned while
> the project maintainer goes off to pay his bills. Several will beat
> Haskell along this or that dimension (again, a different one in each
> case), but their acceptance will be hampered by flame wars on the
> comp.lang.lisp Usenet group.
>
> Endgame: A random old-time Lisp hacker's collection of macros will add up
> to an undocumented, unportable, bug-ridden implementation of 80% of
> Haskell because Lisp is more powerful than Haskell.

(See full story [here](http://winestockwebdesign.com/Essays/Lisp_Curse.html).)

This fragmentation of community is the worst thing that can happen to a language. Don't add to this. Be careful with NIH syndrome, it can bring you to:

http://www.hexstreamsoft.com/introduction.html

Look at this guy carefully, browse his site and GitHub — it's ultimate real-world example of NIH syndrome and community fragmentation problem. He claims to have 50 projects, but guess how many of them he considers “finished”? None, for many years. Believe me, there will never be anything useful from that guy. Wasted life time.

This is why Common Lisp sucks. This is why I will better call it `Value` if everyone has agreed to this.

----

After all, it's your project, I just wanted to save you from wasting time and possible frustration in future. I hope all this stuff does not sound aggressive, or something, I've written this from the best intentions.

**Comment by neongreen** [comment]
> I hope all this stuff does not sound aggressive, or something, I've written this from the best intentions.

It sounds just fine :)

---

I have read your argument as follows:

1. Aeson's market share is too big, so it's unlikely it will be replaced.
2. Aeson isn't even broken enough to *need* to be replaced.
3. Fragmentation of community is a bad idea anyway; CL is the extreme case of it, and CL sucks partly because of it; don't contribute to Haskell becoming CL.
4. Time could be used better than doing this.

I will address each point in turn.

## Market share & replacing Aeson

There are several markets for a JSON library, and they are only loosely connected; it's possible to win in the “somebody needs to read some JSON from a file and do something with it” market while the community of people who use web frameworks and REST APIs would continue to use Aeson – similarly to how pipes/conduit have won in the frameworks/networking market while outside everyone is still mostly using lazy IO (and I can relate – whenever I try to use conduit or pipes for any task I end up *hating* coding for the rest of the day).

(Of course, you might say that the “somebody needs to read some JSON from a file and do something with it” market is much smaller, but a) I'm not sure it is, and b) preventing Haskell from becoming a language optimised solely for web developers is ~~my only goal in life~~ something I will fight for. Together with GTK, Aeson is one of the most frustrating general-use libraries (unlike e.g. Parsec, which may be broken but when it's not it's pleasant to use). And yeah, I'm going to tackle GTK after I'm done with Aeson.)

The reason Megaparsec hasn't attracted many people to it could be that Parsec wasn't frustrating enough. Currently I believe that

* people want to write things other than sites and Twitter API interfaces
* Aeson is frustrating enough
* people hate being frustrated and would do anything in order to avoid frustration

and I'm willing to test my assumptions (which is basically what I'm doing by writing json-x).

Note that I explicitly don't buy the “QWERTY acquired critical degree of adoption” argument. Dvorak hasn't failed; it has (probably?) won in the market for people for whom QWERTY is not good enough. It's not QWERTY's fault that that market is, well, rather tiny. On the other hand, a market for people who want *non-frustrating libraries* is probably much bigger.

## Is Aeson broken?

I think it is. More precisely, I think that no matter how Aeson documentation is rewritten or what tutorials/books/examples/whatever for it exist, it won't ever stop being frustrating. Also, the author of Aeson and I have our differences when it comes to pedagogy, so it's unlikely that I could “officially” improve Aeson *in practice* even if it was possible in theory.

Again: I'm entirely willing to believe that Aeson actually isn't broken and it's just that I have unusually low tolerance of frustration. Individual differences can color our perception greatly; you think QWERTY is absolute nonsense and I think QWERTY is okay; on the other hand, I can't stand Backspace being where it is (so I put it in the center of keyboard), but it was surprising to me when it turned out that other people tolerate Backspace's position just fine. All in all, this library is 70% war against Aeson and 30% “I wonder whether my beliefs are correct” experiment.

## Fragmentation of community

Not all fragmentation is the same; when Bryan wrote `text`, it contributed to the fragmentation in a way that I can't ever hope (or dread?) to achieve. A heuristic I use is “fragmentation is okay when it fixes something unacceptable” (such as slowness of `String`) (and it's similarly unacceptable for any programming language not to have a non-frustrating JSON library), but I'm willing to be proven wrong.

## Wasting time

I've got self-awareness! If I write several “frustration-less” libraries and none of them end up being useful, I'll just change my expectations/models accordingly (as I already did when I tried to fork Pandoc and then realised it was too big for me). But for now, I think it's an experiment worth doing.

**Comment by mrkkrp** [comment]
> The reason Megaparsec hasn't attracted many people to it could be that Parsec wasn't frustrating enough.

I still think that if current Parsec maintainer will continue like this for long enough period of time, Megaparsec will get more market share. Anyway it's good to have fixed Parsec :-)

> I could be wrong about it being broken – for instance, perhaps I simply have unusually low tolerance of frustration.

Last time I used it was OK. For things that I needed from it quick reading of its Haddocks allowed to accomplish everything I wanted with satisfactory results. I'm not entirely sure that this thing needs special tutorial at all — for experienced (or rather non-beginner) Haskeller everything should be quite obvious.

I've seen much worse stuff that I had to use because I cannot rewrite every poor package. (But now I now have to write [`zip`](https://github.com/mrkkrp/zip) to manipulate Zip archives, because there is no decent library for that which I could use without constant headaches.)

----

All in all, good luck with this stuff, I will watch the repo.
